version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
